include(InstallRequiredSystemLibraries)

set(CPACK_PACKAGE_NAME "solver")
set(CPACK_PACKAGE_VENDOR "Arseniy")
set(CPACK_PACKAGE_CONTACT "arseniy@example.com")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "App for solving equations")

set(CPACK_PACKAGE_VERSION_MAJOR ${PVERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${PVERSION_MINOR})
set(CPACK_PACKAGE_VERSION_PATCH ${PVERSION_PATCH})

set(CPACK_GENERATOR "TGZ;ZIP")

set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Arseniy")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.31)")

set(CPACK_RPM_PACKAGE_LICENSE "MIT")
set(CPACK_RPM_PACKAGE_GROUP "Development/Tools")

set(CPACK_PACKAGE_INSTALL_DIRECTORY "solver_${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}")

include(CPack)
