name: Continuous Integration

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential
      
      - name: Configure
        run: cmake -B build -S .
      
      - name: Build
        run: cmake --build build
      
      - name: Test on Linux or macOS
        if: matrix.os != 'windows-latest'
        working-directory: build
        run: |
          chmod +x solver_application/solver
          echo "2 30 60" | ./solver_application/solver
      
      - name: Test on Windows
        if: matrix.os == 'windows-latest'
        working-directory: build
        run: |
          Write-Output "2 30 60" | .\solver_application\Debug\solver.exe
